// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkK8tD_hXQqS5wiMvQT2KIEYE0Mdnb1m8',
    appId: '1:236094728849:web:0e9efa89e3c20c3a42ed30',
    messagingSenderId: '236094728849',
    projectId: 'lectometro',
    authDomain: 'lectometro.firebaseapp.com',
    storageBucket: 'lectometro.firebasestorage.app',
    measurementId: 'G-XKFV1M00PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV42J_HEYCT5Jgd9V9fspzdr7jWznPMBw',
    appId: '1:236094728849:android:25c6880e9a4e07a942ed30',
    messagingSenderId: '236094728849',
    projectId: 'lectometro',
    storageBucket: 'lectometro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1mi59SmxxtrbgJoU2A5Bcu_Uw9cFxgQo',
    appId: '1:236094728849:ios:e0945968595ffada42ed30',
    messagingSenderId: '236094728849',
    projectId: 'lectometro',
    storageBucket: 'lectometro.firebasestorage.app',
    iosClientId: '236094728849-nhh5hihs3o7hflhu1j8g60e1oj1dfomk.apps.googleusercontent.com',
    iosBundleId: 'com.degreeapps.lectometro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkK8tD_hXQqS5wiMvQT2KIEYE0Mdnb1m8',
    appId: '1:236094728849:web:9e3965921ffbb07d42ed30',
    messagingSenderId: '236094728849',
    projectId: 'lectometro',
    authDomain: 'lectometro.firebaseapp.com',
    storageBucket: 'lectometro.firebasestorage.app',
    measurementId: 'G-3CV0GV5ZQC',
  );

}